### ISSUE TITLE
Feature: User can see the list of bestselling books

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see full list of current best selling books by NYT
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User will see full list of books with a short description.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-12 at 10 03 16 AM](https://user-images.githubusercontent.com/106217355/189713751-159a9929-5b78-464e-9c0d-8021d07fc7bc.png)

![Screen Shot 2022-09-12 at 10 02 33 AM](https://user-images.githubusercontent.com/106217355/189713801-04000fc6-89c0-444e-a553-484ccc4e04bb.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] Setup code base
- [x] Install necessary files
- [x] Create necessary directories

⚡ Client Tasks
- [x] Install necessary files, packages
- [x] Create client/ directory 
- [x] Create components/ directory to hold all React components
- [x] create index.jsx file 
 - [x] create app.jsx file
   - [x] send test fetch request 
   - [x] render the page
- [x] Create public/ directory
 - [x] include HTML, CSS

**Comment by yuliia-p** [comment]
![Screen Shot 2022-09-12 at 5 23 30 PM](https://user-images.githubusercontent.com/106217355/189781133-3fcc63bb-eb8a-4784-a73d-f714b4b7dfd0.png)
![Screen Shot 2022-09-12 at 5 23 14 PM](https://user-images.githubusercontent.com/106217355/189781137-f71f7863-21c6-4884-beb1-2174056b1402.png)
