### ISSUE TITLE
Feature: User can see "My Books" list

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/final-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see "My Books" list
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can see all books that were added to list in one place
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-12 at 11 04 57 AM](https://user-images.githubusercontent.com/106217355/189724891-afb75616-fb86-4770-aa88-3ebe0ed69bf0.png)
![Screen Shot 2022-09-12 at 11 05 19 AM](https://user-images.githubusercontent.com/106217355/189724901-08b2fb52-cbca-4e69-a0ed-6a4469904534.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` with GET request using users Id
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update created MyBooks component with fetch req
  - [x] display result on the page

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
