### ISSUE TITLE
Feature: User can delete book from "My Books" list

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/final-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete book from "My Books" list
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can delete book from list while on "My Books" or "More details" page
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-12 at 11 11 32 AM](https://user-images.githubusercontent.com/106217355/189725992-40475ba6-8cd0-450b-83fb-579e1b5a141c.png)
![Screen Shot 2022-09-12 at 11 11 00 AM](https://user-images.githubusercontent.com/106217355/189725994-d3ab1b39-9eee-499c-a00d-60607f429836.png)
![Screen Shot 2022-09-12 at 11 10 47 AM](https://user-images.githubusercontent.com/106217355/189725997-83027c3f-0fe3-4f0c-8bfb-b00ad652202a.png)
![Screen Shot 2022-09-12 at 11 12 10 AM](https://user-images.githubusercontent.com/106217355/189726072-089af9b5-dada-43ea-910d-ca4fe4da162f.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Make sure data is deleted 

### ☁️ Server Tasks

- [x] Update `server/index.js` with:
  - [x]  delete req to usersAddedBooks to delete "userId", "bookId"
  - [x]  delete req to books to delete all data about a book
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update component My Books 
  - [x] Add button 
  - [x] Add modal
  - [x] ocClick will send delete req with book id
 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
