### ISSUE TITLE
Feature: User can search books by a title or an author

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/final-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can search books by a title or an author
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-12 at 11 13 27 AM](https://user-images.githubusercontent.com/106217355/189726504-8e5b2c96-4c5c-4f77-97c2-8f1e2b599faf.png)
![Screen Shot 2022-09-12 at 11 13 13 AM](https://user-images.githubusercontent.com/106217355/189726512-556d70e9-2d21-4b85-b667-7b70d2d4249a.png)

User can search books by a title or an author - the list of results will show up 
## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` if user decides to add a book to list
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update Navbar component 
  - [x] call/render new search component on onChange on input
- [x] Create a component for a search
  - [x] with input form 
  - [x] fetch req to google api with value of input
 - [x] display results on a page 
   - [x] create a new component for list and more details ? (maybe i can reuse some of mine)
  - [x] add post req for saving a book to database ?

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
