### ISSUE TITLE
Feature: User can sing out

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/final-project#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sing out
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can sing out
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-12 at 11 15 50 AM](https://user-images.githubusercontent.com/106217355/189726832-fcf35478-639d-468a-8c49-d7198544e1f2.png)
![Screen Shot 2022-09-12 at 11 16 31 AM](https://user-images.githubusercontent.com/106217355/189726940-7c452a96-4893-4a8f-8a50-e88a143cc14e.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update App component:
  - [x] add state to show drop down menu if user exist and click on profile icon
  - [x] add sign out 
  - [x] remove token from local storage
  - [x] add my books anchor to drop down menu

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
