### ISSUE TITLE
Feature: User can choose category of bestsellers to show

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can choose category of bestsellers to show
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can choose a category of bestsellers (Fiction/Graphic Books/Children's Series/Business etc)
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-12 at 10 21 06 AM](https://user-images.githubusercontent.com/106217355/189717204-b3689f62-ff98-4bb7-bf1c-4da712760db9.png)
![Screen Shot 2022-09-12 at 10 21 19 AM](https://user-images.githubusercontent.com/106217355/189717209-bb108814-8288-449e-925a-754c05eb42fd.png)
![Screen Shot 2022-09-12 at 10 21 41 AM](https://user-images.githubusercontent.com/106217355/189717223-7048ff11-1a21-434e-9d64-661604594b10.png)
![Screen Shot 2022-09-12 at 10 22 00 AM](https://user-images.githubusercontent.com/106217355/189717232-d04555ed-b360-4c71-8de5-ff772ee63688.png)
![Screen Shot 2022-09-12 at 10 22 11 AM](https://user-images.githubusercontent.com/106217355/189717235-b7f2f07c-27ef-441d-b704-4692258d3c4e.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

- [x] Create another request for lists names from NYT API
- [x] Update Navbar component 
  - [x] Add Best Sellers anchor
  - [x] Render dropdown menu with lists names (result of request above)
- [x] Create another request with chosen list name
- [x] Update TopSellers component

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.

**Comment by yuliia-p** [comment]
![Screen Shot 2022-09-13 at 5 18 54 PM](https://user-images.githubusercontent.com/106217355/190031620-f9aa68d8-8a9c-483e-842d-e419049dd398.png)
![Screen Shot 2022-09-13 at 5 19 28 PM](https://user-images.githubusercontent.com/106217355/190031669-40ae96bd-3689-488b-88ae-c9e487117fa1.png)


https://user-images.githubusercontent.com/106217355/190031676-aa7dea3d-273b-477e-a44f-8527f5c62940.mov
