### ISSUE TITLE
Feature: User can see full description of a single book 

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see full description of a single book

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can see full description of a single book with rating and full description

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![189718803-e45d06f5-4fb7-4062-a5db-4445015e78ee](https://user-images.githubusercontent.com/106217355/189722283-e184a5a6-d3c6-4574-87e9-7f804d3f35bd.png)
![189718818-449bd0bd-9add-43df-bdff-aa7fa5f981b6](https://user-images.githubusercontent.com/106217355/189722312-29a3ef17-479a-452f-b2f0-b62ce98c02fd.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] add anchor el to each book
- [x] add hash routing
- [x] if user clicks on an anchor:
  - [x] when the user clicks the book the hash should change to #details?isbn=${book.isbn}
  - [x] get isbn number of a book
  - [x] send a request this time to a google API
  - [x] get full description, rating, genre, buy links (use book_cover img from nty api)
    - [x] render rating (5 stars max) 
  - [x] render page with new information 
- [x] Create new components necessary
- [x] Update App component with new reqs

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
