### ISSUE TITLE
Feature: User can sign up

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can sign up to add books to "want to read" list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![189719766-aa0a24f9-6f9a-47d0-bccd-6a1ee04d1032](https://user-images.githubusercontent.com/106217355/189722591-4c0b24d7-7298-49d1-8590-e69552e2efa9.png)
![189720971-1246c7e1-8a4e-4a27-9cf5-a40c836f97f7](https://user-images.githubusercontent.com/106217355/189722599-95aba905-509d-4a68-b2eb-3854649e8bfc.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] create `schema.sql` for users data
- [x] create `data.sql` for users data

### ☁️ Server Tasks

- [x] Start server
- [x] Update `server/index.js` file 
- [x] Test with HTTPie
- [x] Create app.post request
  - [x] hash password with argon2
- [x] Test if request is fulfilled  
- [x] Check if data is inserted to database
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create new component for authorization 
  - [x] Form element
    - [x] Add handleSubmit(event) for button
    - [x] Add onChange={handleChange} for inputs
- [x] Create new page with signup modal 
- [x] Update App component 
  - [x] Update/add hash routing

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
