### ISSUE TITLE
Feature: User can log in

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log in

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can log in to see and manage books in "want to read" list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-09-16 at 10 08 14 AM](https://user-images.githubusercontent.com/106217355/190692504-01a05859-4d55-4f7c-b3d2-292d742238d8.png)
![Screen Shot 2022-09-16 at 10 08 32 AM](https://user-images.githubusercontent.com/106217355/190692507-9f811233-0512-4aa9-8a7f-3d6b1f1cf332.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` with post req (sign-in)
- [x] check if data accessed
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update components:
  - [x] move modal to App.jsx
  - [ ] add method to change modal from sign-up to sign-in
  - [x]  Update Auth form with sign in fetch req
  - [x] App with new method "sign in"
    - [x] set user's token in local storage
    - [x] pass this method to fetch req for dealing with data (handleSignIn())

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
