### ISSUE TITLE
Feature: User can add book to "My books" list

### ISSUE THREAD

**Issue by yuliia-p** [yuliia-p/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add book to "My books" list
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can add book to "My books" list to keep a book that interested them
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-12 at 10 41 31 AM](https://user-images.githubusercontent.com/106217355/189723719-48a7ab0d-acef-4d19-8b9e-fa1be5f2bc29.png)
![Screen Shot 2022-09-12 at 10 59 32 AM](https://user-images.githubusercontent.com/106217355/189723971-33d3e269-d79b-404c-94a9-619eb3c9f133.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Make sure data is posted

### ☁️ Server Tasks
- [x] Update `server/index.js` with post req
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks
- [x] Update more-details component:
  - [x] Add button which will trigger post req to database with saved book data
- [x] Create a page component to show saved books
- [x] Update Navbar.jsx component with "My Books" anchor
- [x] Update hash routing in App.jsx

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
